### ISSUE TITLE
Existing Xtext grammer Definitions

### ISSUE THREAD

**Issue by astrelsky** [CarloMara/SleigHighlight#3]
So the ghidra devs have released a [SleighEditor](https://github.com/NationalSecurityAgency/ghidra/tree/master/GhidraBuild/EclipsePlugins/GhidraSleighEditor/ghidra.xtext.sleigh/src/ghidra/xtext/sleigh) eclipse plugin for eclipse that uses xtext. I'm wondering if it would be possible to use those files along with this https://github.com/itemis/xtext-languageserver-example to implement some of the features in vscode. At least the syntax highlighting.

**Comment by CarloMara** [comment]
Hi @astrelsky,

next week is gonna be quite busy for me, but I think @ceres-c can look into it.

Carlo

**Comment by ceres-c** [comment]
Hi,
I have been playing with that extension for the last 2 hours. I haven't had any luck building it with Ghidra code, but I believe it's mainly due to my injustified rejection towards enterprise projects. It is definitely doable and it shouldn't take much to someone used to Gradle, but I'm not that person, sorry.

We'd be thankful if you were willing to submit a PR or even roll your own repository basing on that extension :-)

**Comment by astrelsky** [comment]
Not a problem,  just figured I'd put forth the suggestion.  I'll give it a shot myself and if anything becomes of it I'll make a repo for it.
